package database

import (
	"fmt"
	"path/filepath"
	"testing"
	"time"
)

func TestCalculateRecencyScore(t *testing.T) {
	now := time.Now()

	tests := []struct {
		name          string
		lastAccessed  time.Time
		expectedRange [2]float64 // min, max
		description   string
	}{
		{
			name:          "Very Recent (30s ago)",
			lastAccessed:  now.Add(-30 * time.Second),
			expectedRange: [2]float64{0.95, 1.0},
			description:   "Should be near maximum",
		},
		{
			name:          "Recent (5 min ago)",
			lastAccessed:  now.Add(-5 * time.Minute),
			expectedRange: [2]float64{0.6, 0.8},
			description:   "Should be high but declining",
		},
		{
			name:          "Moderate (20 min ago)",
			lastAccessed:  now.Add(-20 * time.Minute),
			expectedRange: [2]float64{0.2, 0.4},
			description:   "Should be moderate",
		},
		{
			name:          "Old (2 hours ago)",
			lastAccessed:  now.Add(-2 * time.Hour),
			expectedRange: [2]float64{0.0, 0.1},
			description:   "Should be very low",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			score := calculateRecencyScore(tt.lastAccessed, now)

			if score < tt.expectedRange[0] || score > tt.expectedRange[1] {
				t.Errorf("%s: got %.3f, want between %.3f and %.3f",
					tt.description, score, tt.expectedRange[0], tt.expectedRange[1])
			}
		})
	}
}

func TestCalculateFrequencyScore(t *testing.T) {
	tests := []struct {
		name          string
		accessCount   int
		expectedRange [2]float64
	}{
		{"Never accessed", 0, [2]float64{0.1, 0.1}},
		{"Once", 1, [2]float64{0.1, 0.1}},
		{"Moderate (5 times)", 5, [2]float64{0.4, 0.6}},
		{"Frequent (20 times)", 20, [2]float64{0.7, 0.85}},
		{"Very frequent (100+ times)", 100, [2]float64{0.85, 0.95}},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			score := calculateFrequencyScore(tt.accessCount)

			if score < tt.expectedRange[0] || score > tt.expectedRange[1] {
				t.Errorf("access_count=%d: got %.3f, want between %.3f and %.3f",
					tt.accessCount, score, tt.expectedRange[0], tt.expectedRange[1])
			}
		})
	}
}

func TestCalculateImportanceScore(t *testing.T) {
	tests := []struct {
		name          string
		path          string
		content       string
		expectedRange [2]float64
		description   string
	}{
		{
			name:          "go.mod (critical)",
			path:          "go.mod",
			content:       "module example.com/test",
			expectedRange: [2]float64{1.0, 1.0},
			description:   "Should be maximum importance",
		},
		{
			name:          "main.go (core)",
			path:          "cmd/main.go",
			content:       "package main\nfunc main() {}",
			expectedRange: [2]float64{0.7, 0.9},
			description:   "Main files are important",
		},
		{
			name:          "schema.go (core infrastructure)",
			path:          "internal/database/schema.go",
			content:       "package database",
			expectedRange: [2]float64{0.6, 0.8},
			description:   "Schema files are important",
		},
		{
			name:          "types.go (interfaces)",
			path:          "internal/types.go",
			content:       "package internal\ntype MyInterface interface{}",
			expectedRange: [2]float64{0.6, 0.8},
			description:   "Type definitions matter",
		},
		{
			name:          "test file",
			path:          "internal/database/store_test.go",
			content:       "package database\nfunc TestStore(t *testing.T) {}",
			expectedRange: [2]float64{0.2, 0.4},
			description:   "Tests are less critical",
		},
		{
			name:          "generated file",
			path:          "internal/generated/models.go",
			content:       "// Code generated by protoc-gen-go",
			expectedRange: [2]float64{0.1, 0.3},
			description:   "Generated files are low priority",
		},
		{
			name:          "vendor file",
			path:          "vendor/github.com/some/package/file.go",
			content:       "package something",
			expectedRange: [2]float64{0.0, 0.2},
			description:   "Vendor files are very low priority",
		},
		{
			name:          "deeply nested utility",
			path:          "internal/utils/helpers/formatting/string/trim.go",
			content:       "package string",
			expectedRange: [2]float64{0.2, 0.4},
			description:   "Deep nesting reduces importance",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			score := calculateImportanceScore(tt.path, tt.content)

			if score < tt.expectedRange[0] || score > tt.expectedRange[1] {
				t.Errorf("%s: path=%s got %.3f, want between %.3f and %.3f",
					tt.description, tt.path, score, tt.expectedRange[0], tt.expectedRange[1])
			}
		})
	}
}

func TestCalculateRelationshipScore(t *testing.T) {
	file1 := RelevanceScore{
		Path:    "internal/database/store.go",
		Content: `package database\nimport "internal/tokenizer"\nfunc (s *Store) DoSomething() {}`,
	}

	file2 := RelevanceScore{
		Path:    "internal/tokenizer/tokenizer.go",
		Content: `package tokenizer\nfunc CountTokens(s string) int { return 0 }`,
	}

	file3 := RelevanceScore{
		Path:    "cmd/main.go",
		Content: `package main\nimport "internal/database"\nfunc main() { store := database.New() }`,
	}

	allFiles := []RelevanceScore{file1, file2, file3}

	tests := []struct {
		name        string
		file        *RelevanceScore
		minExpected float64
		description string
	}{
		{
			name:        "store.go (references tokenizer)",
			file:        &file1,
			minExpected: 0.1,
			description: "Should have some relationships",
		},
		{
			name:        "main.go (references database)",
			file:        &file3,
			minExpected: 0.1,
			description: "Should have some relationships",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			score := calculateRelationshipScore(tt.file, allFiles)

			if score < tt.minExpected {
				t.Errorf("%s: got %.3f, expected at least %.3f",
					tt.description, score, tt.minExpected)
			}
		})
	}
}

func TestCalculateFinalScore(t *testing.T) {
	tests := []struct {
		name string
		rs   RelevanceScore
	}{
		{
			name: "High relevance file",
			rs: RelevanceScore{
				RecencyScore:      0.9,
				FrequencyScore:    0.8,
				ImportanceScore:   1.0,
				RelationshipScore: 0.7,
			},
		},
		{
			name: "Low relevance file",
			rs: RelevanceScore{
				RecencyScore:      0.1,
				FrequencyScore:    0.2,
				ImportanceScore:   0.3,
				RelationshipScore: 0.0,
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			score := calculateFinalScore(&tt.rs)

			// Score should be between 0 and 1
			if score < 0.0 || score > 1.0 {
				t.Errorf("Final score %.3f is out of range [0.0, 1.0]", score)
			}

			// Score should be a weighted average, roughly
			expectedMin := (0.35 * tt.rs.RecencyScore) + (0.20 * tt.rs.FrequencyScore) +
				(0.30 * tt.rs.ImportanceScore) + (0.15 * tt.rs.RelationshipScore)

			if score < expectedMin-0.01 || score > expectedMin+0.01 {
				t.Errorf("Final score %.3f doesn't match expected %.3f", score, expectedMin)
			}
		})
	}
}

func TestSortByScore(t *testing.T) {
	scores := []RelevanceScore{
		{Path: "high.go", Score: 0.9},
		{Path: "low.go", Score: 0.1},
		{Path: "medium.go", Score: 0.5},
	}

	sortByScore(scores)

	// Should be sorted ascending (lowest first)
	if scores[0].Path != "low.go" {
		t.Errorf("First element should be low.go, got %s", scores[0].Path)
	}
	if scores[2].Path != "high.go" {
		t.Errorf("Last element should be high.go, got %s", scores[2].Path)
	}
}

func TestSortByScoreDesc(t *testing.T) {
	scores := []RelevanceScore{
		{Path: "high.go", Score: 0.9},
		{Path: "low.go", Score: 0.1},
		{Path: "medium.go", Score: 0.5},
	}

	sortByScoreDesc(scores)

	// Should be sorted descending (highest first)
	if scores[0].Path != "high.go" {
		t.Errorf("First element should be high.go, got %s", scores[0].Path)
	}
	if scores[2].Path != "low.go" {
		t.Errorf("Last element should be low.go, got %s", scores[2].Path)
	}
}

func TestRelevanceScorer_Integration(t *testing.T) {
	// Create temporary test database
	store, err := New(t.TempDir())
	if err != nil {
		t.Fatalf("Failed to create store: %v", err)
	}
	defer store.Close()

	// Add some test files with different characteristics
	testFiles := []struct {
		path    string
		content string
		tokens  int
	}{
		{
			path:    "go.mod",
			content: "module example.com/test\ngo 1.21",
			tokens:  50,
		},
		{
			path:    "internal/database/store.go",
			content: "package database\nfunc NewStore() *Store { return nil }",
			tokens:  100,
		},
		{
			path:    "internal/database/store_test.go",
			content: "package database\nfunc TestStore(t *testing.T) {}",
			tokens:  80,
		},
		{
			path:    "vendor/github.com/external/lib.go",
			content: "package lib\nfunc Do() {}",
			tokens:  60,
		},
		{
			path:    "cmd/main.go",
			content: "package main\nimport \"internal/database\"\nfunc main() {}",
			tokens:  120,
		},
	}

	// Add files to memory with different access patterns
	for _, tf := range testFiles {
		err := store.UpdateWorkingMemory(tf.path, tf.content)
		if err != nil {
			t.Fatalf("Failed to add file %s: %v", tf.path, err)
		}
		time.Sleep(10 * time.Millisecond) // Ensure different timestamps
	}

	// Access some files multiple times to test frequency scoring
	store.UpdateWorkingMemory("internal/database/store.go", testFiles[1].content)
	store.UpdateWorkingMemory("internal/database/store.go", testFiles[1].content)
	store.UpdateWorkingMemory("cmd/main.go", testFiles[4].content)

	// Get relevance scores
	scorer := store.GetRelevanceScorer()
	scores, err := scorer.CalculateRelevanceScores()
	if err != nil {
		t.Fatalf("Failed to calculate relevance scores: %v", err)
	}

	if len(scores) != len(testFiles) {
		t.Errorf("Expected %d scores, got %d", len(testFiles), len(scores))
	}

	// Verify that go.mod has highest importance
	var goModScore *RelevanceScore
	for i := range scores {
		if scores[i].Path == "go.mod" {
			goModScore = &scores[i]
			break
		}
	}

	if goModScore == nil {
		t.Fatal("go.mod score not found")
	}

	if goModScore.ImportanceScore != 1.0 {
		t.Errorf("go.mod should have importance score of 1.0, got %.3f", goModScore.ImportanceScore)
	}

	// Verify that vendor file has low importance
	var vendorScore *RelevanceScore
	for i := range scores {
		if filepath.Base(filepath.Dir(scores[i].Path)) == "external" {
			vendorScore = &scores[i]
			break
		}
	}

	if vendorScore != nil && vendorScore.ImportanceScore > 0.3 {
		t.Errorf("Vendor file should have low importance, got %.3f", vendorScore.ImportanceScore)
	}

	// Verify that frequently accessed files have higher frequency scores
	var storeScore *RelevanceScore
	for i := range scores {
		if scores[i].Path == "internal/database/store.go" {
			storeScore = &scores[i]
			break
		}
	}

	if storeScore != nil && storeScore.AccessCount < 2 {
		t.Errorf("store.go should have been accessed multiple times, got %d", storeScore.AccessCount)
	}
}

func TestRelevanceScorer_SelectFilesForEviction(t *testing.T) {
	store, err := New(t.TempDir())
	if err != nil {
		t.Fatalf("Failed to create store: %v", err)
	}
	defer store.Close()

	// Add files with known token counts
	files := []struct {
		path   string
		tokens int
	}{
		{"important/file1.go", 1000},
		{"vendor/file2.go", 2000},    // Low importance
		{"test/file3_test.go", 1500}, // Test file, lower importance
		{"core/main.go", 1200},       // Main file, high importance
	}

	for _, f := range files {
		content := fmt.Sprintf("package test\n// This file has approximately %d tokens worth of content", f.tokens)
		// Pad content to approximately match token count
		for i := 0; i < f.tokens/10; i++ {
			content += " placeholder"
		}
		err := store.UpdateWorkingMemory(f.path, content)
		if err != nil {
			t.Fatalf("Failed to add file %s: %v", f.path, err)
		}
	}

	scorer := store.GetRelevanceScorer()

	// Test eviction with a tight budget
	targetTokens := 3000 // Should force eviction of ~2-3 files
	toEvict, err := scorer.SelectFilesForEviction(targetTokens)
	if err != nil {
		t.Fatalf("SelectFilesForEviction failed: %v", err)
	}

	if len(toEvict) == 0 {
		t.Error("Expected some files to be selected for eviction")
	}

	// Verify that vendor and test files are more likely to be evicted
	evictedLowPriority := false
	for _, path := range toEvict {
		if filepath.Base(filepath.Dir(path)) == "vendor" ||
			filepath.Base(filepath.Dir(path)) == "test" {
			evictedLowPriority = true
			break
		}
	}

	if !evictedLowPriority {
		t.Log("Note: Expected low-priority files to be evicted, but depends on scoring")
	}

	// Verify main.go is NOT in eviction list
	for _, path := range toEvict {
		if filepath.Base(path) == "main.go" {
			t.Error("main.go should not be evicted (high importance)")
		}
	}
}

func TestRelevanceScorer_GetTopFiles(t *testing.T) {
	store, err := New(t.TempDir())
	if err != nil {
		t.Fatalf("Failed to create store: %v", err)
	}
	defer store.Close()

	// Add test files
	testFiles := []string{
		"go.mod",
		"internal/database/store.go",
		"cmd/main.go",
		"test/helper_test.go",
		"vendor/external/lib.go",
	}

	for _, path := range testFiles {
		err := store.UpdateWorkingMemory(path, "package test")
		if err != nil {
			t.Fatalf("Failed to add file %s: %v", path, err)
		}
	}

	scorer := store.GetRelevanceScorer()

	// Get top 3 files
	topFiles, err := scorer.GetTopFiles(3)
	if err != nil {
		t.Fatalf("GetTopFiles failed: %v", err)
	}

	if len(topFiles) != 3 {
		t.Errorf("Expected 3 top files, got %d", len(topFiles))
	}

	// Verify they're sorted by score (descending)
	for i := 1; i < len(topFiles); i++ {
		if topFiles[i].Score > topFiles[i-1].Score {
			t.Errorf("Top files not sorted correctly: score[%d]=%.3f > score[%d]=%.3f",
				i, topFiles[i].Score, i-1, topFiles[i-1].Score)
		}
	}

	// go.mod should likely be in top 3
	foundGoMod := false
	for _, f := range topFiles {
		if f.Path == "go.mod" {
			foundGoMod = true
			break
		}
	}

	if !foundGoMod {
		t.Log("Note: Expected go.mod in top 3, but depends on access patterns")
	}
}

func TestTruncatePath(t *testing.T) {
	tests := []struct {
		path      string
		maxLen    int
		wantStart string
	}{
		{"short.go", 20, "short.go"},
		{"very/long/path/to/some/deep/file.go", 20, "...p/deep/file.go"},
	}

	for _, tt := range tests {
		t.Run(tt.path, func(t *testing.T) {
			result := truncatePath(tt.path, tt.maxLen)

			if len(result) > tt.maxLen {
				t.Errorf("truncatePath(%q, %d) = %q (len=%d), want len <= %d",
					tt.path, tt.maxLen, result, len(result), tt.maxLen)
			}
		})
	}
}
