package writer

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"unicode/utf8"

	"github.com/atotto/clipboard"
)

type OutputStrategy interface {
	Init() error
	Write(absPath, relPath string) error
	Close() error
	ShouldSkip(path string) bool
	Name() string
}

// --- Strategy 1: Concat (Single File) ---

type ConcatStrategy struct {
	OutputPath    string
	file          *os.File
	TokenEstimate int
	Minify        bool
}

func NewConcatStrategy(path string, minify bool) *ConcatStrategy {
	return &ConcatStrategy{OutputPath: path, Minify: minify}
}

func (c *ConcatStrategy) Name() string { return "Concat" }

func (c *ConcatStrategy) Init() error {
	if err := os.MkdirAll(filepath.Dir(c.OutputPath), 0755); err != nil {
		return err
	}
	f, err := os.Create(c.OutputPath)
	if err != nil {
		return err
	}
	c.file = f
	fmt.Fprintf(c.file, "# Codebase Context Dump\n")
	fmt.Fprintf(c.file, "Generated by codepicker\n\n")
	return nil
}

func (c *ConcatStrategy) ShouldSkip(path string) bool {
	return path == c.OutputPath
}

func (c *ConcatStrategy) Write(absPath, relPath string) error {
	f, err := os.Open(absPath)
	if err != nil {
		return err
	}
	defer f.Close()

	content, err := io.ReadAll(f)
	if err != nil {
		return err
	}

	if !utf8.Valid(content) {
		return nil
	}

	if c.Minify {
		content = c.minifyContent(content, filepath.Ext(relPath))
	}

	ext := strings.TrimPrefix(filepath.Ext(relPath), ".")
	if ext == "" {
		ext = "text"
	}

	fmt.Fprintf(c.file, "## File: %s\n", relPath)
	fmt.Fprintf(c.file, "```%s\n", ext)
	n, err := c.file.Write(content)
	if err != nil {
		return err
	}

	// Ensure newline at end of block
	if len(content) > 0 && content[len(content)-1] != '\n' {
		c.file.Write([]byte("\n"))
		n++
	}

	c.TokenEstimate += n / 4
	fmt.Fprintf(c.file, "```\n\n")
	return nil
}

func (c *ConcatStrategy) minifyContent(content []byte, ext string) []byte {
	lines := strings.Split(string(content), "\n")
	var kept []string

	// Determine comment prefix and type
	prefix := ""
	isMarkdown := false

	switch strings.ToLower(ext) {
	case ".go", ".js", ".ts", ".java", ".c", ".cpp", ".rs", ".cs", ".php", ".swift", ".kt":
		prefix = "//"
	case ".py", ".rb", ".sh", ".yaml", ".yml", ".toml", ".dockerfile", "makefile", ".pl":
		prefix = "#"
	case ".sql", ".lua":
		prefix = "--"
	case ".md", ".txt", ".rst":
		isMarkdown = true
	}

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		// 1. Handle Empty Lines
		if trimmed == "" {
			// If it's markdown, we MUST keep empty lines to preserve paragraphs.
			// If it's code, we can safely strip them to save tokens.
			if isMarkdown {
				kept = append(kept, line)
			}
			continue
		}

		// 2. Remove Comments
		// Only remove if a prefix is defined AND the line starts with it.
		// We do not strip comments from Markdown files (prefix is "").
		if prefix != "" && strings.HasPrefix(trimmed, prefix) {
			continue
		}

		// Keep the line (preserves indentation)
		kept = append(kept, line)
	}

	return []byte(strings.Join(kept, "\n"))
}

func (c *ConcatStrategy) Close() error {
	return c.file.Close()
}

// --- Strategy 2: Copy (Directory Mirror) ---

type CopyStrategy struct {
	OutputDir string
}

func NewCopyStrategy(dir string) *CopyStrategy {
	return &CopyStrategy{OutputDir: dir}
}

func (c *CopyStrategy) Name() string { return "Copy" }

func (c *CopyStrategy) Init() error {
	return os.MkdirAll(c.OutputDir, 0755)
}

func (c *CopyStrategy) ShouldSkip(path string) bool {
	return filepath.HasPrefix(path, c.OutputDir)
}

func (c *CopyStrategy) Write(absPath, relPath string) error {
	targetPath := filepath.Join(c.OutputDir, relPath)
	if err := os.MkdirAll(filepath.Dir(targetPath), 0755); err != nil {
		return err
	}

	src, _ := os.Open(absPath)
	defer src.Close()

	dst, _ := os.Create(targetPath)
	defer dst.Close()

	io.Copy(dst, src)
	return nil
}

func (c *CopyStrategy) Close() error { return nil }

// --- Strategy 3: Tree (Visual Map) ---

type TreeOptions struct {
	CopyToClipboard bool
	OutPath         string
}

type TreeStrategy struct {
	opts   TreeOptions
	buffer *bytes.Buffer
}

func NewTreeStrategy(opts TreeOptions) *TreeStrategy {
	return &TreeStrategy{
		opts:   opts,
		buffer: &bytes.Buffer{},
	}
}

func (t *TreeStrategy) Name() string { return "Tree" }

func (t *TreeStrategy) Init() error {
	header := "PROJECT STRUCTURE:\n.\n"
	fmt.Print(header)
	t.buffer.WriteString(header)
	return nil
}

func (t *TreeStrategy) ShouldSkip(path string) bool {
	if t.opts.OutPath != "" {
		return strings.HasSuffix(path, t.opts.OutPath)
	}
	return false
}

func (t *TreeStrategy) Write(absPath, relPath string) error {
	parts := strings.Split(relPath, string(os.PathSeparator))
	depth := len(parts) - 1
	filename := parts[len(parts)-1]

	indent := ""
	for i := 0; i < depth; i++ {
		indent += "│   "
	}

	line := fmt.Sprintf("%s├── %s\n", indent, filename)
	fmt.Print(line)
	t.buffer.WriteString(line)
	return nil
}

func (t *TreeStrategy) Close() error {
	result := t.buffer.String()

	if t.opts.OutPath != "" {
		if err := os.WriteFile(t.opts.OutPath, t.buffer.Bytes(), 0644); err != nil {
			return fmt.Errorf("failed to save tree file: %w", err)
		}
		fmt.Printf("\n📄 Tree saved to: %s", t.opts.OutPath)
	}

	if t.opts.CopyToClipboard {
		if err := clipboard.WriteAll(result); err != nil {
			return fmt.Errorf("failed to copy to clipboard: %w", err)
		}
		fmt.Println("\n📋 Tree copied to clipboard!")
	}
	fmt.Println()
	return nil
}

