package main

import (
	"fmt"
	"log"
	"os"
	"time"

	"github.com/david22573/codepicker/internal/database"
)

func main() {
	tmpDir, _ := os.MkdirTemp("", "eviction_demo")
	defer os.RemoveAll(tmpDir)

	store, err := database.New(tmpDir)
	if err != nil {
		log.Fatal(err)
	}
	defer store.Close()

	fmt.Println("🧠 Context Eviction Simulation")
	fmt.Println("------------------------------")

	// 1. Add "Important" files (based on rules in internal/database/relevance.go)
	fmt.Println("1. Adding critical configuration files...")
	store.UpdateWorkingMemory("go.mod", "module test\ngo 1.22")          // High score
	store.UpdateWorkingMemory("main.go", "package main\nfunc main() {}") // High score

	// 2. Add "Noise" files (older access, generated content)
	fmt.Println("2. Adding noise/generated files...")
	store.UpdateWorkingMemory("pkg/generated/api.go", "// Code generated by tool. DO NOT EDIT.\n func Stub() {}")

	// Manually age the generated file in the DB to simulate old access
	// (We access the DB directly for the demo since UpdateWorkingMemory resets the timestamp)
	db := store.DB()
	oldTime := time.Now().Add(-24 * time.Hour)
	db.Exec("UPDATE memory_files SET last_accessed = ? WHERE path = ?", oldTime, "pkg/generated/api.go")

	// 3. Run Scoring Debugger
	fmt.Println("\n📊 Calculating Relevance Scores:")
	scorer := store.GetRelevanceScorer()

	debugOutput, err := scorer.DebugScores()
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(debugOutput)

	fmt.Println("\n📝 Observation:")
	fmt.Println("   - go.mod should be at the top (Critical file)")
	fmt.Println("   - main.go should be high (Core logic)")
	fmt.Println("   - pkg/generated/api.go should be low (Old access + Generated content)")
}
