package context

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/david22573/codepicker/domain/errors"
)

// Config defines the rules for context generation
type Config struct {
	MaxTokens       int
	IncludePatterns []string
	ExcludePatterns []string
	ProjectRoot     string
}

type Builder struct{}

func NewBuilder() *Builder {
	return &Builder{}
}

// Build generates a markdown string containing the project context
func (b *Builder) Build(cfg Config) (string, error) {
	var sb strings.Builder
	sb.WriteString("# Codebase Context Dump\n")
	sb.WriteString(fmt.Sprintf("Generated by codepicker\n\n"))

	currentTokens := 0
	filesProcessed := 0

	// 1. Collect all candidate files first (for deterministic sorting)
	var candidates []string

	err := filepath.Walk(cfg.ProjectRoot, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil
		}
		if info.IsDir() {
			// Always exclude hidden dirs and vendor
			if strings.HasPrefix(info.Name(), ".") && info.Name() != "." {
				return filepath.SkipDir
			}
			if info.Name() == "vendor" || info.Name() == "node_modules" {
				return filepath.SkipDir
			}
			return nil
		}

		relPath, _ := filepath.Rel(cfg.ProjectRoot, path)

		// Check User Excludes
		for _, pat := range cfg.ExcludePatterns {
			matched, _ := filepath.Match(pat, relPath)
			if matched {
				return nil
			}
		}

		// Check User Includes (if specified, otherwise include all)
		if len(cfg.IncludePatterns) > 0 {
			included := false
			for _, pat := range cfg.IncludePatterns {
				matched, _ := filepath.Match(pat, relPath)
				if matched {
					included = true
					break
				}
			}
			if !included {
				return nil
			}
		}

		candidates = append(candidates, relPath)
		return nil
	})

	if err != nil {
		return "", errors.NewSystem("context.Build", "walk failed", err)
	}

	// 2. Sort candidates to ensure deterministic output
	sort.Strings(candidates)

	// 3. Read files and enforce budget
	for _, relPath := range candidates {
		fullPath := filepath.Join(cfg.ProjectRoot, relPath)
		content, err := os.ReadFile(fullPath)
		if err != nil {
			continue // Skip unreadable
		}

		// Heuristic: 1 token ~= 4 chars
		estTokens := len(content) / 4

		if currentTokens+estTokens > cfg.MaxTokens {
			sb.WriteString(fmt.Sprintf("\n> ⚠️ Context limit reached. Skipping remaining %d files.\n", len(candidates)-filesProcessed))
			break
		}

		// Append to Output
		sb.WriteString(fmt.Sprintf("## File: %s\n", relPath))
		sb.WriteString("```text\n")
		sb.WriteString(string(content))
		sb.WriteString("\n```\n\n")

		currentTokens += estTokens
		filesProcessed++
	}

	return sb.String(), nil
}
