package cmd

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/david22573/codepicker/internal/shadow"
	"github.com/david22573/codepicker/internal/tui"
	"github.com/david22573/codepicker/internal/ui"
	"github.com/spf13/cobra"
)

var (
	autoApprove   bool
	acceptPattern string
	rejectPattern string
	useTUI        bool
)

var applyCmd = &cobra.Command{
	Use:   "apply",
	Short: "Review and apply changes from the shadow filesystem",
	Long:  `Iterates through files generated by the agent in the shadow directory. Performs atomic backups before applying changes.`,
	RunE: func(cmd *cobra.Command, args []string) error {

		if ui.Standard == nil {
			ui.Standard = ui.NewConsoleUI()
		}

		sm, err := shadow.NewManager(srcDir)
		if err != nil {
			return fmt.Errorf("failed to init shadow manager: %w", err)
		}

		files, err := sm.ListShadowFiles()
		if err != nil {
			return fmt.Errorf("failed to list shadow files: %w", err)
		}

		if len(files) == 0 {
			ui.Standard.Success("No pending changes in shadow directory.")
			return nil
		}

		// FILTERING
		var pendingFiles []string
		for _, f := range files {
			if acceptPattern != "" && matchesPattern(f, acceptPattern) {
				pendingFiles = append(pendingFiles, f)
				continue
			}
			if rejectPattern != "" && matchesPattern(f, rejectPattern) {
				continue
			}
			pendingFiles = append(pendingFiles, f)
		}

		if len(pendingFiles) == 0 {
			ui.Standard.Warn("No files matched criteria.")
			return nil
		}

		// TUI MODE
		if useTUI && !autoApprove {
			return tui.Run(sm, pendingFiles)
		}

		// CLI MODE
		ui.Standard.Info("📦 Pending Changes:")
		var rows [][]string
		for _, f := range pendingFiles {
			rows = append(rows, []string{f, "Pending"})
		}
		ui.Standard.Table([]string{"File Path", "Status"}, rows)
		fmt.Println("")

		if !autoApprove {
			choice, _, _ := ui.Standard.Select("How to proceed?", []string{
				"Apply All (Batch)",
				"Interactive Review",
				"Discard All",
			})

			switch choice {
			case 0:
				// Fallthrough to batch apply
			case 1:
				return runInteractiveReview(sm, pendingFiles)
			case 2:
				return sm.Cleanup()
			default:
				return nil
			}
		}

		return runBatchApply(sm, pendingFiles)
	},
}

// runBatchApply attempts to apply all files with rollback capability
func runBatchApply(sm *shadow.Manager, files []string) error {
	ui.Standard.Info("🚀 Applying %d files...", len(files))

	var backups = make(map[string]string) // file -> backupPath
	var applied []string

	for _, file := range files {
		backupPath, err := sm.ApplyAtomic(file)
		if err != nil {
			ui.Standard.Error("❌ Failed to apply %s: %v", file, err)

			if ui.Standard.Confirm("Apply failed. Rollback previous changes?", true) {
				rollback(sm, backups, applied)
				return fmt.Errorf("operation aborted and rolled back")
			}
			return fmt.Errorf("operation stopped (partial apply)")
		}

		backups[file] = backupPath
		applied = append(applied, file)
		ui.Standard.Info("  ✓ %s", file)
	}

	ui.Standard.Success("✨ Successfully applied %d files.", len(applied))
	sm.Cleanup()
	return nil
}

func rollback(sm *shadow.Manager, backups map[string]string, applied []string) {
	ui.Standard.Warn("↺ Rolling back changes...")
	for _, f := range applied {
		backup := backups[f]
		if err := sm.Restore(f, backup); err != nil {
			ui.Standard.Error("  CRITICAL: Failed to restore %s from %s", f, backup)
		} else {
			fmt.Printf("  Restored %s\n", f)
		}
	}
}

func runInteractiveReview(sm *shadow.Manager, files []string) error {
	for i, file := range files {
		fmt.Println("\n" + strings.Repeat("=", 60))
		ui.Standard.Info("[%d/%d] Reviewing: %s", i+1, len(files), file)
		fmt.Println(strings.Repeat("=", 60))

		diff, _ := sm.PreviewDiff(file)
		fmt.Println(diff)

		choice, _, _ := ui.Standard.Select("Action?", []string{
			"Apply",
			"Skip",
			"Apply All Remaining",
			"Quit",
		})

		switch choice {
		case 0: // Apply
			if _, err := sm.ApplyAtomic(file); err != nil {
				ui.Standard.Error("Failed to apply: %v", err)
			} else {
				ui.Standard.Success("Applied.")
			}
		case 1: // Skip
			ui.Standard.Warn("Skipped.")
		case 2: // Apply Remaining
			remaining := files[i:]
			return runBatchApply(sm, remaining)
		case 3: // Quit
			return nil
		}
	}

	if ui.Standard.Confirm("Clean up remaining shadow files?", true) {
		sm.Cleanup()
	}
	return nil
}

func matchesPattern(file, pattern string) bool {
	if pattern == "" {
		return false
	}
	matched, _ := filepath.Match(pattern, file)
	return matched
}

func init() {
	rootCmd.AddCommand(applyCmd)
	applyCmd.Flags().BoolVarP(&autoApprove, "yes", "y", false, "Automatically apply all changes without prompting")
	applyCmd.Flags().StringVar(&acceptPattern, "accept", "", "Glob pattern to auto-accept (e.g. '*.go')")
	applyCmd.Flags().StringVar(&rejectPattern, "reject", "", "Glob pattern to auto-reject (e.g. '*.md')")
	applyCmd.Flags().BoolVar(&useTUI, "tui", true, "Use interactive TUI for review (disable for CI/CD)")
}
