package cmd

import (
	"fmt"
	"path/filepath"

	"github.com/david22573/codepicker/internal/shadow"
	"github.com/david22573/codepicker/internal/tui"
	"github.com/david22573/codepicker/internal/ui"
	"github.com/spf13/cobra"
)

var (
	autoApprove   bool
	acceptPattern string
	rejectPattern string
	interactive   bool
)

var applyCmd = &cobra.Command{
	Use:   "apply",
	Short: "Review and apply changes from the shadow filesystem",
	Long:  `Iterates through files generated by the agent in the shadow directory. Performs atomic backups before applying changes.`,
	RunE: func(cmd *cobra.Command, args []string) error {

		if ui.Standard == nil {
			ui.Standard = ui.NewConsoleUI()
		}

		sm, err := shadow.NewManager(srcDir)
		if err != nil {
			return fmt.Errorf("failed to init shadow manager: %w", err)
		}

		files, err := sm.ListShadowFiles()
		if err != nil {
			return fmt.Errorf("failed to list shadow files: %w", err)
		}

		if len(files) == 0 {
			ui.Standard.Success("No pending changes in shadow directory.")
			return nil
		}

		var pendingFiles []string
		for _, f := range files {
			if rejectPattern != "" && matchesPattern(f, rejectPattern) {
				continue
			}
			if acceptPattern != "" {
				if matchesPattern(f, acceptPattern) {
					pendingFiles = append(pendingFiles, f)
				}
				continue
			}
			pendingFiles = append(pendingFiles, f)
		}

		if len(pendingFiles) == 0 {
			ui.Standard.Warn("No files matched criteria.")
			return nil
		}

		// Phase 1: Explicit interactive mode check
		if interactive && !autoApprove {
			return tui.Run(sm, pendingFiles)
		}

		ui.Standard.Info("📦 Pending Changes:")
		var rows [][]string
		for _, f := range pendingFiles {
			rows = append(rows, []string{f, "Pending"})
		}
		ui.Standard.Table([]string{"File Path", "Status"}, rows)
		fmt.Println("")

		if !autoApprove {
			choice, _, _ := ui.Standard.Select("How to proceed?", []string{
				"Apply All (Batch)",
				"Interactive Review (TUI)",
				"Discard All",
			})

			switch choice {
			case 0:
				// Fallthrough to batch apply
			case 1:
				return runInteractiveReview(sm, pendingFiles)
			case 2:
				return sm.Cleanup()
			default:
				return nil
			}
		}

		return runBatchApply(sm, pendingFiles)
	},
}

func runBatchApply(sm *shadow.Manager, files []string) error {
	ui.Standard.Info("🚀 Applying %d files...", len(files))

	var backups = make(map[string]string)
	var applied []string

	for _, file := range files {
		backupPath, err := sm.ApplyAtomic(file)
		if err != nil {
			ui.Standard.Error("❌ Failed to apply %s: %v", file, err)
			ui.Standard.Warn("⚠️  Batch application failed. Initiating auto-rollback...")
			rollback(sm, backups, applied)
			return fmt.Errorf("operation aborted and rolled back due to error on %s", file)
		}

		backups[file] = backupPath
		applied = append(applied, file)
		ui.Standard.Info("  ✓ %s", file)
	}

	ui.Standard.Success("✨ Successfully applied %d files.", len(applied))
	sm.Cleanup()
	return nil
}

func rollback(sm *shadow.Manager, backups map[string]string, applied []string) {
	ui.Standard.Warn("↺ Rolling back changes...")
	for i := len(applied) - 1; i >= 0; i-- {
		f := applied[i]
		backup := backups[f]
		if err := sm.Restore(f, backup); err != nil {
			ui.Standard.Error("  CRITICAL: Failed to restore %s from %s", f, backup)
		} else {
			fmt.Printf("  Restored %s\n", f)
		}
	}
}

func runInteractiveReview(sm *shadow.Manager, files []string) error {
	// Re-route to TUI if selected from menu
	return tui.Run(sm, files)
}

func matchesPattern(file, pattern string) bool {
	if pattern == "" {
		return false
	}
	matched, _ := filepath.Match(pattern, file)
	return matched
}

func init() {
	rootCmd.AddCommand(applyCmd)
	applyCmd.Flags().BoolVarP(&autoApprove, "yes", "y", false, "Automatically apply all changes without prompting")
	applyCmd.Flags().StringVar(&acceptPattern, "accept", "", "Glob pattern to auto-accept (e.g. '*.go') - acts as a whitelist")
	applyCmd.Flags().StringVar(&rejectPattern, "reject", "", "Glob pattern to auto-reject (e.g. '*.md') - takes precedence")
	applyCmd.Flags().BoolVarP(&interactive, "interactive", "t", false, "Use interactive TUI for review")
}
