package cmd

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/david22573/codepicker/internal/shadow"
	"github.com/david22573/codepicker/internal/ui"
	"github.com/spf13/cobra"
)

var (
	autoApprove   bool
	acceptPattern string
	rejectPattern string
)

var applyCmd = &cobra.Command{
	Use:   "apply",
	Short: "Review and apply changes from the shadow filesystem",
	Long:  `Iterates through files generated by the agent in the shadow directory. Shows a summary first, then reviews changes file-by-file.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		// Initialize UI if not already done globally
		if ui.Standard == nil {
			ui.Standard = ui.NewConsoleUI()
		}

		sm, err := shadow.NewManager(srcDir)
		if err != nil {
			return fmt.Errorf("failed to init shadow manager: %w", err)
		}

		files, err := sm.ListShadowFiles()
		if err != nil {
			return fmt.Errorf("failed to list shadow files: %w", err)
		}

		if len(files) == 0 {
			ui.Standard.Success("No pending changes in shadow directory.")
			return nil
		}

		// 1. Show Summary Table
		ui.Standard.Info("📦 Pending Changes Summary:")
		var rows [][]string
		for _, f := range files {
			// A simple status check could be added here (New vs Mod)
			rows = append(rows, []string{f, "Pending"})
		}
		ui.Standard.Table([]string{"File Path", "Status"}, rows)
		fmt.Println("") // Spacer

		// 2. Iterate and Review
		appliedCount := 0
		skippedCount := 0

		for i, file := range files {
			ui.Standard.Info("[%d/%d] Reviewing: %s", i+1, len(files), file)

			// Check auto-patterns
			if matchesPattern(file, acceptPattern) {
				if err := applyChange(sm, file); err != nil {
					ui.Standard.Error("Failed to apply %s: %v", file, err)
				} else {
					appliedCount++
				}
				continue
			}

			if matchesPattern(file, rejectPattern) {
				ui.Standard.Warn("Skipped %s (matches reject pattern)", file)
				skippedCount++
				continue
			}

			// Generate Diff
			diff, err := sm.PreviewDiff(file)
			if err != nil {
				ui.Standard.Warn("Could not generate diff for %s: %v", file, err)
				continue
			}

			fmt.Println(strings.Repeat("-", 60))
			fmt.Println(diff)
			fmt.Println(strings.Repeat("-", 60))

			if autoApprove {
				if err := applyChange(sm, file); err != nil {
					ui.Standard.Error("Failed to apply %s: %v", file, err)
				} else {
					appliedCount++
				}
				continue
			}

			// Interactive Prompt
			choice, _, err := ui.Standard.Select("Action?", []string{"Apply", "Skip", "Apply All Remaining", "Quit"})
			if err != nil {
				break
			}

			switch choice {
			case 0: // Apply
				if err := applyChange(sm, file); err != nil {
					ui.Standard.Error("Failed to apply %s: %v", file, err)
				} else {
					appliedCount++
				}
			case 1: // Skip
				ui.Standard.Warn("Skipped.")
				skippedCount++
			case 2: // Apply All
				autoApprove = true
				if err := applyChange(sm, file); err != nil {
					ui.Standard.Error("Failed to apply %s: %v", file, err)
				} else {
					appliedCount++
				}
				ui.Standard.Info("Auto-approving remaining files...")
			case 3: // Quit
				ui.Standard.Info("👋 Review aborted.")
				goto Summary
			}
		}

	Summary:
		// 3. Cleanup Logic
		if appliedCount > 0 || skippedCount > 0 {
			ui.Standard.Info("\nSummary: %d applied, %d skipped.", appliedCount, skippedCount)
		}

		// Only ask to clear if we actually processed the queue
		remaining, _ := sm.ListShadowFiles()
		if len(remaining) == 0 {
			sm.Cleanup()
			ui.Standard.Success("Shadow directory cleaned.")
		} else {
			if ui.Standard.Confirm("Clear remaining shadow files?", false) {
				sm.Cleanup()
				ui.Standard.Success("Shadow directory cleaned.")
			}
		}

		return nil
	},
}

func matchesPattern(file, pattern string) bool {
	if pattern == "" {
		return false
	}
	matched, _ := filepath.Match(pattern, file)
	return matched
}

func applyChange(sm *shadow.Manager, file string) error {
	if err := sm.Apply(file); err != nil {
		return err
	}
	ui.Standard.Success("Applied: %s", file)
	return nil
}

func init() {
	rootCmd.AddCommand(applyCmd)
	applyCmd.Flags().BoolVarP(&autoApprove, "yes", "y", false, "Automatically apply all changes without prompting")
	applyCmd.Flags().StringVar(&acceptPattern, "accept", "", "Glob pattern to auto-accept (e.g. '*.go')")
	applyCmd.Flags().StringVar(&rejectPattern, "reject", "", "Glob pattern to auto-reject (e.g. '*.md')")
}
