package cmd

import (
	"fmt"
	"os"

	"github.com/david22573/codepicker/internal/constants"
	"github.com/spf13/cobra"
)

var forceInit bool

// defaultConfigTemplate defines the structure of the generated YAML file.
// We use a string template here (instead of marshalling a struct) to include
// helpful comments for the end user.
const defaultConfigTemplate = `# .codepicker.yml
# Generated by codepicker init

src: .
output: codepicker_context.md
minify: true
tokens: false

# File extensions to include (add more as needed)
include:
  - .go
  - .ts
  - .js

# Directories to exclude
exclude:
  - .git
  - node_modules
  - vendor
  - codepicker_out

# AI integration settings
ai:
  model: %s
  temperature: 0.7
`

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Generate a default configuration file",
	Long:  `Creates a .codepicker.yml file in the current directory with default settings.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		filename := ".codepicker.yml"

		// Check if file exists to prevent accidental overwrite
		if _, err := os.Stat(filename); err == nil {
			if !forceInit {
				return fmt.Errorf("configuration file %s already exists (use --force to overwrite)", filename)
			}
			appLogger.Warn(fmt.Sprintf("Overwriting existing %s", filename))
		}

		// Populate the template with the current default model from constants
		content := fmt.Sprintf(defaultConfigTemplate, constants.DefaultModel)

		// Write the file
		if err := os.WriteFile(filename, []byte(content), 0644); err != nil {
			return fmt.Errorf("failed to write config file: %w", err)
		}

		appLogger.Info(fmt.Sprintf("Created default configuration: %s", filename))
		fmt.Println("\n✨ Initialized! You can now edit .codepicker.yml to customize your settings.")
		return nil
	},
}

func init() {
	rootCmd.AddCommand(initCmd)
	initCmd.Flags().BoolVarP(&forceInit, "force", "f", false, "Overwrite existing config file")
}
