package constants

import "time"

const (
	// Application Info
	AppName = "codepicker"

	// API Defaults
	DefaultModel    = "xiaomi/mimo-v2-flash:free"
	MinAPIKeyLength = 10
	MaxRetries      = 3
	RetryDelay      = 1 * time.Second

	// File System limits
	MaxFileSize    = 100 * 1024 * 1024 // 100MB
	DefaultOutPath = "codepicker_context.md"

	// Output Formatting
	ContextHeader = "# Codebase Context Dump\n"
	GeneratedBy   = "Generated by codepicker\n\n"
)
